version: '3.9'
services:
  database:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: node:18
    container_name: backend-container
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
    command: >
      sh -c "npm install &&
             npm run dev"

  frontend:
    image: node:18
    container_name: frontend-container
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: >
      sh -c "npm install &&
             npm start"

volumes:
  postgres_data:
